function set_plot_default_properties
reset(groot)
set(groot,...
    'defaultFigureUnits','centimeters', ...
    'defaultFigurePosition',[4 4 18 14],...
    'defaultAxesXScale','log',...
    'defaultAxesYScale','log',...
    'defaultAxesXGrid','on',...
    'defaultAxesXMinorGrid','on',...
    'defaultAxesYGrid','on',...
    'defaultAxesYMinorGrid','on', ...
    'defaultTextInterpreter','latex',...
    'defaultTextInterpreter','tex',...
    'defaultAxesTitleFontWeight','bold')
end